[package]
name = "demo_fleet"
version = "0.1.0"

[dependencies]
protologic_core = { path = "../protologic_core" }
rand = { version = "0.8.5" }
rand_chacha = { version = "0.3.1" }

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
panic = "abort"